### ISSUE TITLE
text entry dock might make sense to display vertically or dock elsewhere when the bottom dock is already tall

### ISSUE THREAD

**Issue by ericfont** [JoshuaBonn1/MuseScore#10]
looking at https://github.com/JoshuaBonn1/MuseScore/commit/2ed1b0ad03427529306419584ca48cb7e728d106 I notice that thanks to fix for #1, we now have a bit of a problem with the text entry toolbar taking up too much space (and just looks a little ugly):

![screenshot at 2017-08-07 23-04-44](https://user-images.githubusercontent.com/6502474/29054541-d0dd5884-7bc4-11e7-8987-de3bb22cf015.png)

I still stand by the need for that fix and think we should keep it.  However, there is a question of whether there is a better way to present the text control toolbar when we have the presence of the timeline docked.  Maybe the text toolbar could be laid out vertically instead of horizontally, that way it doesn't take up so much horizontal space.  Or maybe we can have the text entry toolbar be docked somewhere else, such as the top of musescore?  I don't know.  Maybe we should ask lasconic.

**Comment by JoshuaBonn1** [comment]
For now, I will make the adjustment that I did for the texttool for #11. These are relatively small edits, so reverting them would not be a problem

**Comment by JoshuaBonn1** [comment]
As mentioned in #11, the piano keyboard has the same issue as #1 which the fix is displayed above. So, the piano keyboard, drum entry, and text tools should all be taken into consideration with this change

**Comment by ericfont** [comment]
ok.  I made an possible change idea #13 as a way to help coexistance.

**Comment by lasconic** [comment]
Maybe have a look to https://doc.qt.io/qt-5/qmainwindow.html#splitDockWidget

**Comment by ericfont** [comment]
Taking a look at that link, I see 

> "The orientation specifies how the space is divided: A Qt::Horizontal split places the second dock widget to the right of the first; a Qt::Vertical split places the second dock widget below the first."

I'm thinking using a Qt::Vertical split would make best use of space for this case.

**Comment by JoshuaBonn1** [comment]
Well, using splitDockWidget to make a vertical split works (which looks very good), however it is still possible to undock it and put it on the side, leading to the same problem as before. There are also abilities to stack all of them (I'd rather not allow that functionallity for texttools/drumtools and the timeline; I'd rather just have pianotool and timeline tabify). I've looked up things for making it not possible and all I've found have been QMainWindow options for all dock widgets--definitely not a good idea.

**Comment by ericfont** [comment]
I'd say it is "ok" if someone undocks one and deliberately places them side by side...if the user wants that then fine.  Mainly what I care about here is the default behavior, so I would say have the default behavior be to split dock widget vertically if the user has timeline or text toolbar already up and brings up the other.

**Comment by lasconic** [comment]
I agree with @ericfont

**Comment by JoshuaBonn1** [comment]
Applied vertical split for timeline and drumtools/texttools. Any issues with this, make a new issue.
