### ISSUE TITLE
prevent the timeline from being smaller than the height of the metarows + one cell

### ISSUE THREAD

**Issue by ericfont** [JoshuaBonn1/MuseScore#12]
Take a look at the right vertical scroll bar:

![screenshot at 2017-08-07 23-21-43](https://user-images.githubusercontent.com/6502474/29054910-2fe7716e-7bc7-11e7-90db-d900346708e5.png)

Notice that it is displayed from the very top of timeline to the bottom of timeline.  However, I believe it should only extend from the top of the actual cell data to the bottom of the cell data.  This would be similar to how the bottom scroll bar extends.  This will properly communicate to the user that the scroll bar only actually controls the cell data.

The way it is now becomes more problematic when the height of the timeline window is not tall enough to fit any cell data, in which case it looks like:

![screenshot at 2017-08-07 23-23-27](https://user-images.githubusercontent.com/6502474/29054942-6f4ffa4c-7bc7-11e7-9754-f635fb903690.png)

And in which case the scroll bar has no apparent effect.  User might think the scrollbar is broken in this case.

**Comment by JoshuaBonn1** [comment]
I understand the reasoning behind this. However, I believe this might be a very large edit, as i am unsure if just rewritting the builtin functions or breaking the timeline grid and meta rows into two different widgets will work... I'm really not sure.

**Comment by ericfont** [comment]
oh, that must be because the horizontal scrollbar is using the built in extension but only extends on as far as it does because it uses the built in divider.  How about this: can use use a vertical divider as well as horizontal divider?  Then that would also allow the meta rows to scroll by themselves.  Edit: I see this was your second option.

**Comment by ericfont** [comment]
Well I do think breaking it into two widgets is the proper way that this should have been done...it is unfortunate that neither of us realized this earlier.

**Comment by ericfont** [comment]
as a stop gap measure, I think you will need to prevent the timeline from being smaller than the height of the metarows + one cell.  That way there is always some scroll-able cell region.

**Comment by JoshuaBonn1** [comment]
That is definitely something I have thought about, however with the time of the GSoC running out, I'm worried that such a large change for a rather small issue would cause me to run out of time to polish up the  timeline and make it much more presentable. I would say a stopgap measure would be a much better solution right now. (There is tons of code based on them being two widgets for the full timeline to do with overlapping the meta rows and selections as well as interactions between the labels and the main grid that would have to be rewritten)

**Comment by ericfont** [comment]
ok, then do the stopgap measure right now.  Should be simple.

**Comment by ericfont** [comment]
I'm calling it a bug since scrollbar doesn't work in this situation.
