### ISSUE TITLE
Change default dock

### ISSUE THREAD

**Issue by ericfont** [JoshuaBonn1/MuseScore#13]
Thinking about issues #10 and #11, I'm wondering that a lot of conflict could be avoided by having less things contend for and having to share the same dock.  

Either way to handle this would be:
1. the timeline default dock could be moved to the top dock while the others keep the bottom dock, or
2. the other tools default docks (primarily text edit and drum toolbar) could be changed to the top dock while the timeline (and piano keyboard) keep the bottom dock)

one disadvantage of 2 is that the scoreview would necessarily move down on the screen whenever user edits text or drums.

**Comment by JoshuaBonn1** [comment]
Closing due to change of approach. See #10.

**Comment by ericfont** [comment]
Ok.
