### ISSUE TITLE
Timeline minimum permitted width (especially when docked) should be at least width of longest label + width of a few cells

### ISSUE THREAD

**Issue by ericfont** [JoshuaBonn1/MuseScore#14]
A problem arises when I first dock the timeline on top dock, bring up the piano keyboard on bottom dock, and then drag the timeline from the top dock to the either side of the piano keyboard in the bottom dock, without first manually changing the timeline window's width:

![screenshot at 2017-08-08 00-37-09](https://user-images.githubusercontent.com/6502474/29056556-b9c90b5e-7bd1-11e7-944a-081516b872e1.png)

The piano keyboard takes most all of the horizontal space.  There is no way to adjust the divider position either.  I can fix the width of the timeline only by undocking it, adjusting its width, and then redocking it next to the piano keyboard.

I propose to ensure the timeline always has a reasonable minimum width.  I would say that should be at least wide enough to hold width of first column plus 5 cells (that way can display the measure numbers 1 & 5 by default and so that the width of the cell area is about the same width as the first column).

**Comment by ericfont** [comment]
this should also prevent user from dragging the window while undocked to be smaller than that minimum width.  Want to avoid the possibility of a dumb user accidentally making the timeline window so small to be useless, such as the following:

![screenshot at 2017-08-08 00-45-57](https://user-images.githubusercontent.com/6502474/29056727-fb90d76e-7bd2-11e7-81eb-1bedb54e6570.png)

**Comment by JoshuaBonn1** [comment]
Huh, there is some strange behavior to be found here. If you dock it on the right of the piano keyboard, it doesn't allow for resizing (which should not be happening), but if it is docked on the left, resizing is allowed. I definitely agree with the minimum sizes, and those should be addressed all around the timeline.

**Comment by ericfont** [comment]
I can confirm "If you dock it on the right of the piano keyboard, it doesn't allow for resizing (which should not be happening), but if it is docked on the left, resizing is allowed."

You might have to make an edit to the piano keyboard to allow for that.

**Comment by JoshuaBonn1** [comment]
@ericfont Using the logic of making sure the default position works #10 , the piano keyboard starts out on the right side which allows for resizing left and right, however it restricts vertical because of the minimum and maximum height being the same for the piano keyboard. If I increase the maximum height on the piano keyboard, it works. Should I continue working on trying to make the piano keyboard/timeline resizeable if the piano keyboard is on the left side? Or just go with it?

**Comment by ericfont** [comment]
Sounds like piano keyboard shouldn't enforce a maximum height when it is docked, so it can be gracious with other docked windows who want to expand vertically.

> Should I continue working on trying to make the piano keyboard/timeline resizeable if the piano keyboard is on the left side? 

I guess that is not a significant concern.  What I want more is ensuring the timeline has a minimum width.
