### ISSUE TITLE
tooltip for all meta row labels: "M[#], [type/name]"

### ISSUE THREAD

**Issue by ericfont** [JoshuaBonn1/MuseScore#17]
Since we have tooltips for most stuff on the timeline, for consistency sake I think have it for all.  (Rehearsal marks and Time sigs currently don't).  Also I think follow the similar format "M[#], [type/name]" as is done for cells...whereby if the text is already displayed in the label, then write the type of label in the tooltip (since no need to duplcate that text), else just write the text as is done currently in the tooltip.  So I think:

- "M 1, Tempo"
- "M 1, Time Signature"
- "M 1, Rehearsal Mark"
- "M 1, E major/C# minor"
- "M 1, Double barline"
- "M 1, Jump"
- "M 1, Marker"

Should be very simple.  I'm mainly only suggesting this nitpick cause I can't think of other ways to improve timeline at this time.

**Comment by IsaacWeiss** [comment]
"...can't think of other ways to improve timeline at this time." I left a couple comments at https://musescoe.org/en/user/1190941/blog/[yyyy]/[mm]/[dd]/gsoc-2017-timeline-navigation-weekly-report-12. (Yes, I subscribed to this fork so I could get notifications of discussions here. XD)
