### ISSUE TITLE
Use rounded corners for meta values

### ISSUE THREAD

**Issue by JoshuaBonn1** [JoshuaBonn1/MuseScore#2]
Round the right corners of the meta values to help distinguish between different meta values.

**Comment by ericfont** [comment]
Not necessarily always the right corner.  Rather:

- For left-justified labels (most of them), round the right corners.
- For right-justified labels (Jumps & End Repeats when uncollapsed), round the left corners.

That way it is easy to tell where the label is "anchored" to.
