### ISSUE TITLE
Always display closed eye next to hidden instrument name?

### ISSUE THREAD

**Issue by ericfont** [JoshuaBonn1/MuseScore#7]
To make sure user knows the instrument is hidden, write it's name in grey instead of black.

Also I'm thinking it might make sense to always display the closed eye icon next to the name of the hidden instruments, to make it more clear.

**Comment by JoshuaBonn1** [comment]
This was addressed in my latest commit. However, the second part is different.

**Comment by JoshuaBonn1** [comment]
I could see the usefulness of this and it should not be too hard to implement. I'll give it a night and decide tomorrow

**Comment by ericfont** [comment]
great.  No biggie if you decide against it.

**Comment by JoshuaBonn1** [comment]
I've decided against it, I rather like how that information doesn't remain--especially for those that don't find it important. I definitely understand why it'd be useful, but to keep it consistent with the rest of the timeline, I'd prefer it to not be there unless the mouse is there.

**Comment by ericfont** [comment]
ok.
